services:
  flask-app:
    container_name: flask-app
    restart: always
    env_file: .env
    build: .
    ports:
      - "5005:5005"
    networks:
      - web_network

  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /var/www/certbot:/var/www/certbot  # ✅ Nginx serves ACME challenges here
      - ~/j8iraids/certbot/etc:/etc/letsencrypt  # ✅ Store SSL certs on host
    networks:
      - web_network
    depends_on:
      - flask-app

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - /var/www/certbot:/var/www/certbot  # ✅ Certbot challenge files are stored here
      - ~/j8iraids/certbot/etc:/etc/letsencrypt  # ✅ Certbot saves SSL certs on host
    depends_on:
      - nginx
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
