version: '3.8'

services:
  flask-app:
    container_name: flask-app
    restart: always
    env_file: .env
    build: .
    ports:
      - "5005:5005"  # Map host port to container port
    networks:
      - web_network

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    networks:
      - web_network
    depends_on:
      - flask-app


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet --agree-tos --email utbisalan@gmail.com; sleep 12h & wait $${!}; done'"
    depends_on:
      - nginx
    networks:
      - web_network

  volumes:
    certbot-etc:
    certbot-www:

networks:
  web_network:
    driver: bridge
