services:
  flask-app:
    container_name: flask-app
    restart: always
    env_file: .env
    build: .
    ports:
      - "5005:5005"
    networks:
      - web_network

  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - certbot-www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt  # ✅ Use Docker volume instead of a host path
    networks:
      - web_network
    depends_on:
      - flask-app

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet --agree-tos --email your-email@example.com; sleep 12h & wait $${!}; done'"
    depends_on:
      - nginx
    networks:
      - web_network

volumes:
  certbot-etc:
  certbot-www:

networks:
  web_network:
    driver: bridge
